### ISSUE TITLE
variants of the "Certification of Vaccination" pdf

### ISSUE THREAD

**Issue by JosephAmalfitanoSSA** [GSA/SaferFederalWorkforce.gov#56]
https://github.com/GSA/SaferFederalWorkforce.gov/blob/310bbc06b7aed459bcc7823b83bed02431954cf4/_faq/vaccinations.html

I've noticed that the page links to two distinct PDF versions of the Certification of Vaccination form. Based on the content of the forms, to me it seems that one is explicitly for employees and the other is for both employees and/or non employees?

Do you know if there will be only one variant when all is said and done, or the path is two? The one that is linked from employees (CertificationVaccinationEmployees.pdf) looks very rough drafty compared to the other (CertificationVaccinationPRAv7.pdf). 

thanks @DaveSkender  😄

**Comment by DaveSkender** [comment]
Hey Joseph, you're right, there are two variants of the certification here.

Regarding this two-form policy and the future, it's best to pose your question directly to the Safer Federal Workforce Task Force at `saferfederalworkforce@gsa.gov` -- I can only really address technical issues with the website here.
